### ISSUE TITLE
Turn blue led off

### ISSUE THREAD

**Issue by b0kar** [zigpy/zigpy-zigate#79]
Hello Doudz,

I cannot turn off zigate blue led since migrating to zha.
How can I do that?

Here si what I tried in configuration.yaml

```
zha:
  zigpy_config:
    zigpy_zigate:
      set_led: False

```

```
zha:
  zigpy_config:
    zigpy_zigate:
      set_led: 0
```
